name: boring_form
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  provider: ^6.1.2
  file_picker: ^8.0.3
  universal_html: ^2.2.4
  omni_datetime_picker: ^1.1.0
  calendar_date_picker2: ^1.0.2

  dropdown_button2:
    git:
      url: git@github.com:BoringStuff-SRL/drop_down.git
  
  boring_table:
    git:
      url: git@github.com:BoringStuff-SRL/FlutterBoringTable.git
      ref: develop
  
  boring_dropdown:
    git:
      url: https://github.com/LeoRc01/boring_dropdown
      ref: main

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: null

