name: boring_form
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=1.17.1"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  provider: ^6.0.5
  file_picker: ^5.2.6
  
  dropdown_button2:
    git:
      url: https://github.com/enzo-desimone/drop_down.git
  
  boring_table:
    git:
      url: https://github.com/fradesa/FlutterBoringTable.git
      ref: slidable

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null

