name: boring_form
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  file_picker: ^9.0.2
  omni_datetime_picker: ^2.1.0
  calendar_date_picker2: ^1.1.9

  dropdown_button2:
    git:
      url: git@github.com:BoringStuff-SRL/drop_down.git
  
  boring_table:
    git:
      url: git@github.com:BoringStuff-SRL/FlutterBoringTable.git
      ref: develop
  
  boring_dropdown:
    git:
      url: https://github.com/LeoRc01/boring_dropdown
      ref: main

dev_dependencies:
  flutter_lints: ^5.0.0
  intl: ^0.20.1
  flutter_test:
    sdk: flutter

flutter: null

