name: boring_form
description: A new Flutter package project.
version: 0.0.1

publish_to: "none"

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.2
  file_picker: ^9.2.2 
  universal_html: ^2.2.4
  flutter_svg: ^2.0.10+1
  omni_datetime_picker: ^2.0.5
  collection: ^1.19.1
  widget_zoom: ^0.0.4
  month_year_picker: ^0.4.0+1
  super_drag_and_drop: ^0.8.24
  boring_ui:
    git:
      url: git@github.com:BoringStuff-SRL/BoringUI.git
      ref: refactoring_form
  rrule: ^0.2.16

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
