name: boring_form
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  provider: ^6.0.5
  file_picker: ^5.3.1
  universal_html: ^2.2.3


  dropdown_button2:
    git:
      url: https://github.com/enzo-desimone/drop_down.git
  
  boring_table:
    git:
      url: https://github.com/BoringStuff-SRL/FlutterBoringTable.git
      ref: develop
  omni_datetime_picker: ^1.0.8
  calendar_date_picker2: ^0.5.3

  

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: null

